### ISSUE TITLE
use 3.0 端口(A或typec)插 iphone 无法识别

### ISSUE THREAD

**Issue by moxnet** [leggod/Hackintosh-B460M-MORTAR#12]
把 iphone 插到 usb 2.0 接口，能正常识别，Finder 中能正常展示iphone设备；
但插到 usb 3.0，无法识别（插3.0 A口无任何反应，插 type-c 口能充电但 Finder 无法认出 iphone 设备）；

大家有碰到这个问题么？是不是需要定制 USB？

**Comment by leggod** [comment]
原装线插typec是好的，我打过几次包

**Comment by zhouta0** [comment]
？？？我的b460m迫击炮没有C口哇，也没有无线网卡，可是我用大佬的efi无修改成功黑苹果。

**Comment by zhouta0** [comment]
红米4k显示器的typec口连接电脑主板的typec口确实没有反应，不能输出图像，但是好像开机的时候能听到滋啦一声的声音。

**Comment by moxnet** [comment]
> 把 iphone 插到 usb 2.0 接口，能正常识别，Finder 中能正常展示iphone设备； 但插到 usb 3.0，无法识别（插3.0 A口无任何反应，插 type-c 口能充电但 Finder 无法认出 iphone 设备）；
> 
> 大家有碰到这个问题么？是不是需要定制 USB？

重新定制USB后解决。
