### ISSUE TITLE
能连接WiFi，但是搜不到其他的WiFi了

### ISSUE THREAD

**Issue by linpeilie** [leggod/Hackintosh-B460M-MORTAR#15]
intel的网卡，刚装好的时候可以搜到WiFi，连上之后，就搜不到别的WiFi了，用的8.4.3
<img width="290" alt="image" src="https://user-images.githubusercontent.com/26854247/223137516-2d711ecb-b4a5-4c0b-84e0-b6f2b3ba1f4c.png">

**Comment by leggod** [comment]
若须更好的体验请购买白卡
