### ISSUE TITLE
B460M迫击炮 + 10700k + 核显 + BCM94360(免驱卡)

### ISSUE THREAD

**Issue by yaohl0911** [leggod/Hackintosh-B460M-MORTAR#2]
B460M迫击炮 + 10700k + 核显 + BCM94360(免驱卡)是不是也是删 Kernel-add 中 所有相关Intel选项的项目或者Enabled = false

**Comment by leggod** [comment]
是的，把 因特尔和 博通  相关的蓝牙WiFi 驱动项删了，或者false

**Comment by yaohl0911** [comment]
好久没折腾了，opencore的版本比较低了，回去更新下。再问下，这个efi会自动启动吗？我现在关机之后经常自动启动。

**Comment by leggod** [comment]
我没遇到过，你说的自动启动，是在使用中，还是关机后

**Comment by leggod** [comment]
那应该不是OC的问题，可能是你bios 的设置问题，或许设置了键盘唤醒之类的

**Comment by leggod** [comment]
bios 里面还有一个断电后的来电重启，不需要你应该都关掉

**Comment by yaohl0911** [comment]
看到个解决方案：在BIOS禁用USB唤醒，但是会导致鼠标和键盘无法唤醒，电源键可以唤醒。回头试下

**Comment by yaohl0911** [comment]
好的，我去试试

**Comment by yaohl0911** [comment]
![Xnip2022-09-08_23-24-15](https://user-images.githubusercontent.com/33289635/189162112-277a120a-60d6-4d53-8adc-b467d0b827fd.png)
取消以上三项的使能，自己生成序列号，可以正常开机，但是显示有点模糊，但是能正常使用，也没有卡顿

**Comment by leggod** [comment]
你用的0.8.4？我自己用的0.8.2，贼稳定。那三个上面的两个也可以取消，因为你是白卡

**Comment by yaohl0911** [comment]
嗯，用的你这个0.8.4，显示会模糊。后来换了我一直用的一个仓的0.8.3版本，macos升到了最新版，目前看没啥问题。有时间再看看你们俩的配置有哪些差异

**Comment by leggod** [comment]
仓库发我看看

**Comment by yaohl0911** [comment]
https://github.com/rennai/Hackintosh-10900ES-B460M-MORTAR

**Comment by leggod** [comment]
谢谢，我瞄一下，大概心里能猜到，你没有独显的话，就是dp那里的配置不一样

**Comment by yaohl0911** [comment]
有时间我也看看，感谢无私分享
