### ISSUE TITLE
升级步骤以及只用核显的疑问

### ISSUE THREAD

**Issue by codenamem27** [leggod/Hackintosh-B460M-MORTAR#27]
大神好, 

我现在还在用BigSur, 最近打算升级到Sonoma. 请问以下升级步骤是否正确?

1. 下载新版本的OpenCore以及EFI,
2. 将新的OpenCore 和 EFI 覆盖现有文件
3. 更改三码
4. 进入系统然后运行Sonoma安装文件进行升级

另外如果我只有核显是否需要更改EFI禁止独立显卡? 如果是的话需要改哪里呢? 
非常感谢!

**Comment by leggod** [comment]
![image](https://github.com/user-attachments/assets/59fdac4a-e32a-4d6b-9b11-e95a3446a584)
兄嘚，这么全的文档多看一下啦

**Comment by codenamem27** [comment]
非常感谢!
